import { test, expect } from "@playwright/test";
const VIEWPORTS = { desktop: { width: 1280, height: 800 }, mobile: { width: 375, height: 812 } } as const;
const DYNAMIC_SELECTORS = ["[data-testid='timestamp']", "[data-testid='random-value']", "[data-testid='wallet-address']", ".recharts-wrapper", "time"];
async function maskDynamic(page: import("@playwright/test").Page) { for (const selector of DYNAMIC_SELECTORS) { const els = page.locator(selector); const count = await els.count(); for (let i = 0; i < count; i++) { await els.nth(i).evaluate((el: HTMLElement) => { el.style.visibility = "hidden"; }); } } }
async function toggleTheme(page: import("@playwright/test").Page, dark: boolean) { if (dark) { await page.getByRole("button", { name: /switch to dark mode/i }).click().catch(() => {}); await page.getByRole("button", { name: /dark/i }).click().catch(() => {}); } else { await page.getByRole("button", { name: /switch to light mode/i }).click().catch(() => {}); await page.getByRole("button", { name: /light/i }).click().catch(() => {}); } await page.waitForLoadState("networkidle"); }
test.describe("Visual regression – Component Dark Mode", () => {
  test("Input component renders correctly in light theme", async ({ page }) => { await page.setViewportSize(VIEWPORTS.desktop); await page.goto("/"); await maskDynamic(page); await expect(page).toHaveScreenshot("component-input-light.png", { fullPage: true, maxDiffPixelRatio: 0.02 }); });
  test("Input component renders correctly in dark theme", async ({ page }) => { await page.setViewportSize(VIEWPORTS.desktop); await page.goto("/"); await toggleTheme(page, true); await maskDynamic(page); await expect(page).toHaveScreenshot("component-input-dark.png", { fullPage: true, maxDiffPixelRatio: 0.02 }); });
  test("Button component renders correctly in both themes", async ({ page }) => { await page.setViewportSize(VIEWPORTS.desktop); await page.goto("/"); await maskDynamic(page); await expect(page).toHaveScreenshot("component-button-light.png", { fullPage: true, maxDiffPixelRatio: 0.02 }); await toggleTheme(page, true); await maskDynamic(page); await expect(page).toHaveScreenshot("component-button-dark.png", { fullPage: true, maxDiffPixelRatio: 0.02 }); });
  test("Card component renders correctly in both themes", async ({ page }) => { await page.setViewportSize(VIEWPORTS.desktop); await page.goto("/"); await maskDynamic(page); await expect(page).toHaveScreenshot("component-card-light.png", { fullPage: true, maxDiffPixelRatio: 0.02 }); await toggleTheme(page, true); await maskDynamic(page); await expect(page).toHaveScreenshot("component-card-dark.png", { fullPage: true, maxDiffPixelRatio: 0.02 }); });
});
